site_name: Plotynium
site_url: https://bourbonut.github.io/plotynium

repo_url: https://github.com/bourbonut/plotynium

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  search:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          docstring_style: numpy
          show_if_no_docstring: true
          show_docstring_attributes: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          separate_signature: true
          signature_crossrefs: true
          merge_init_into_class: true
          parameter_headings: true
          show_bases: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bourbonut/plotynium/
      name: Plotynium on Github

nav:
  - Home: index.md
  - Introduction:
    - introduction.md
  - Colorschemes:
    - colorschemes/interpolations.md
    - colorschemes/schemes.md
  - API:
    - api/index.md
    - api/plot.md
    - "plotynium.marks":
      - api/marks/area_y.md
      - api/marks/axis_x.md
      - api/marks/axis_y.md
      - api/marks/bar_y.md
      - api/marks/dot.md
      - api/marks/grid_x.md
      - api/marks/grid_y.md
      - api/marks/line.md
      - api/marks/rule_y.md
    - api/interpolations.md
    - api/schemes.md
    - api/options.md
    - api/types.md
 
copyright: Copyright &copy; bourbonut
